compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.0.cjs

packageExtensions:
  'styled-components@*':
    peerDependenciesMeta:
      'react-is':
        optional: true